default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "" %>
  host:     <%= ENV["POSTGRES_HOST"] || "127.0.0.1" %>
  port:     <%= ENV["POSTGRES_PORT"] || 5432 %>

test:
  primary:
    <<: *default
    database: <%= ENV["POSTGRES_DB"] || "prairie_naturals_test" %>
