# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: prairie_naturals_development
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>

test:
  <<: *default
  database: prairie_naturals_test
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>

production:
  primary:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate

  queue:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate

  cable:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
