default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME", "akinpope") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Lawyer@85") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prairie_naturals_development

test:
  <<: *default
  database: prairie_naturals_test

production:
  primary: &primary_production
    <<: *default
    database: prairie_naturals_production
    username: prairie_naturals
    password: <%= ENV["PRAIRIE_NATURALS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: prairie_naturals_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: prairie_naturals_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: prairie_naturals_production_cable
    migrations_paths: db/cable_migrate
