name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: prairie_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: prairie_naturals_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U prairie_user -d prairie_naturals_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    env:
      RAILS_ENV: test
      DATABASE_URL: ""                 # ensure Rails uses env-driven config
      POSTGRES_USER: prairie_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prairie_naturals_test
      POSTGRES_HOST: postgres          # IMPORTANT: service hostname
      POSTGRES_PORT: 5432
      PGPASSWORD: password

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for Postgres (pg_isready + SQL)
        run: |
          echo "Waiting for Postgres on $POSTGRES_HOST:$POSTGRES_PORT..."
          for i in {1..120}; do  # ~4 minutes
            if pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
              if psql "host=$POSTGRES_HOST port=$POSTGRES_PORT dbname=$POSTGRES_DB user=$POSTGRES_USER sslmode=disable" -c "SELECT 1" >/dev/null 2>&1; then
                echo "Postgres is ready (attempt $i)."
                exit 0
              fi
            fi
            echo "Postgres not ready yet... ($i)"
            sleep 2
          done
          echo "Postgres failed to become ready in time."
          exit 1

      - name: Prepare DB
        run: bundle exec rails db:prepare --trace

      - name: RuboCop
        run: bundle exec rubocop -A

      - name: Run tests (Minitest)
        run: DISABLE_BOOTSNAP=1 bin/rails test --backtrace
        # If you use RSpec instead:
        # run: DISABLE_BOOTSNAP=1 bundle exec rspec --format documentation
