name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: prairie_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: prairie_naturals_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U prairie_user -d prairie_naturals_test"
          --health-interval=10s --health-timeout=5s --health-retries=10

    env:
      RAILS_ENV: test
      POSTGRES_USER: prairie_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prairie_naturals_test
      POSTGRES_HOST: postgres   # service hostname (NOT localhost)
      POSTGRES_PORT: 5432

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Prepare DB
        run: bundle exec rails db:prepare

      - name: RuboCop
        run: bundle exec rubocop -A

      - name: Run tests (Minitest)
        run: DISABLE_BOOTSNAP=1 bin/rails test --backtrace
        # If you use RSpec instead, replace the line above with:
        # run: DISABLE_BOOTSNAP=1 bundle exec rspec --format documentation
